apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounting

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - horizon-deployment.yaml
  - reverb-deployment.yaml
  - service.yaml
  - mysql-statefulset.yaml
  - redis.yaml
  - ingress.yaml
  - network-policy.yaml
