apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounting-storage
  namespace: accounting
  labels:
    app: accounting-laravel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
